all:
  vars:
    ip_master: 192.168.100.10
  children:
    master:
      hosts:
        kmaster:
          ansible_host: 192.168.100.10
    nodes:
      hosts:
        knode1:
          ansible_host: 192.168.100.10
        knode2:
          ansible_host: 192.168.100.11

